// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/google/wire"
	"github.com/hertz-contrib/swagger"
	"gorm.io/gorm"
	"strconv"
	"yikou-ai-go-teach/config"
	"yikou-ai-go-teach/docs"
	"yikou-ai-go-teach/internal/dal"
	"yikou-ai-go-teach/internal/handler"
	"yikou-ai-go-teach/internal/logic"
	"yikou-ai-go-teach/internal/router"
	"yikou-ai-go-teach/internal/service"
)

// Injectors from wire.go:

// InitializeApp 初始化所有依赖（依赖图）
func InitializeApp() (*server.Hertz, error) {
	configConfig := config.InitConfig()
	db := dal.InitDB(configConfig)
	userService := logic.NewUserService(db)
	userHandler := handler.NewUserHandler(userService)
	hertz := initServer(configConfig, userHandler, db)
	return hertz, nil
}

// wire.go:

// 配置依赖
var configSet = wire.NewSet(config.InitConfig)

// 数据库依赖
var dbSet = wire.NewSet(dal.InitDB)

// Service依赖
var serviceSet = wire.NewSet(logic.NewUserService, wire.Bind(new(service.IUserService), new(*logic.UserService)))

// Handler依赖
var handlerSet = wire.NewSet(handler.NewUserHandler)

// initServer 初始化 Web 服务器
func initServer(cfg *config.Config, userHandler *handler.UserHandler, db *gorm.DB) *server.Hertz {
	docs.SwaggerInfo.
		Host = fmt.Sprintf("localhost:%d", cfg.Server.Port)
	docs.SwaggerInfo.
		BasePath = cfg.Server.ContextPath

	swaggerPath := fmt.Sprintf("http://localhost:%d%s/swagger/doc.json", cfg.Server.Port, cfg.Server.ContextPath)
	url := swagger.URL(swaggerPath)

	h := server.Default(server.WithHostPorts(":"+strconv.Itoa(cfg.Server.Port)), server.WithBasePath(cfg.Server.ContextPath))
	router.RegisterRoutes(h, url, db, userHandler)
	return h
}
